shell = "zsh"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-bat]
github = "fdellwing/zsh-bat"
